nome = ('Juan')
idade = int('16')
linguafav = ('python')
ano_atual = int('2025')
anon = ano_atual - idade
print ('Meu nome é {}' .format (nome))
print ('Eu tenho {} anos de idade' .format (idade))
print ('Minha liguagem de programação favorita é {}' .format (linguafav))
print ('O ano em que estamos atualmente é {} ' .format (ano_atual))
print ('O ano em que eu a=nasci é {}' .format (anon))